### ISSUE TITLE
Is it possible to control the LED flashlight without using Camera Interface?

### ISSUE THREAD

**Issue by vikramsvdd** [ranjan-malav/MorseLight#4]
As in the question, i need to control the LED directly at 100 or 200 hz, is it possible to control the LED of android directly rather than accessing it through android?

**Comment by ranjan-malav** [comment]
I'm not aware of any method that allows you to use the flashlight without accessing it through the new camera APIs.
Maybe some old deprecated code can do this(http://androidxref.com/5.0.0_r2/xref/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/FlashlightController.java).
Controlling the flashlight for any specific frequency is independent of how you are accessing it anyway. So maybe you can do that through new Camera APIs?

**Comment by vikramsvdd** [comment]
Ah a nice question, but the peoblem is the Camera API's limits the frequency to max out at around 40hz. So accessing the LED through camera interface is not a viable solution for me. That's why i wanted to know is there any way where i can bypass the camera interface and access the LED driver directly. But as far as people commented, it is not possible coz to directly control LED i need to mess with the hardware drivers and user apps by default dont have access, but i have heard there is a method known as rooting which allows me to do that.
